### ISSUE TITLE
Showing thresholded and unthresholded maps using outlines and transparency

### ISSUE THREAD

**Issue by chrisfilo** [KirstieJane/BrainsForPublication#11]
I rally like this visualisation by the MRN http://mialab.mrn.org/datavis/index.html

![sample_aod](https://cloud.githubusercontent.com/assets/238759/14570722/95d9c216-02fa-11e6-8026-466c2e225682.JPG)

**Comment by KirstieJane** [comment]
Hi @chrisfilo - I really like this too. I've actually already made an issue (#7) proposing it - based on your comments in the stack channel so I'm going to close this one, but we should definitely promote using these sorts of images!
